server:
  port: 8001
  servlet:
    session:
          timeout: 600000
    context-path: /wlm
spring:
  application:
      name: wlm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wlm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 0

# 开启sql打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

knife4j:
  enable: true